CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_report_no VARCHAR NOT NULL UNIQUE,
    product_name VARCHAR NOT NULL,
    company_name VARCHAR NOT NULL,
    primary_function_raw TEXT,
    functional_ingredient_raw TEXT,
    product_type VARCHAR,
    production_status VARCHAR,
    source_updated_at DATE NOT NULL,
    source_name VARCHAR NOT NULL
);

CREATE TABLE ingredient_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_name VARCHAR NOT NULL UNIQUE,
    ingredient_code VARCHAR UNIQUE,
    ingredient_category VARCHAR NOT NULL,
    support_status VARCHAR NOT NULL
);

CREATE TABLE ingredient_synonyms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_master_id BIGINT NOT NULL,
    raw_text VARCHAR NOT NULL UNIQUE,
    CONSTRAINT fk_ingredient_synonyms_ingredient_master
        FOREIGN KEY (ingredient_master_id) REFERENCES ingredient_master (id)
);

CREATE TABLE functional_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_master_id BIGINT,
    recognition_no VARCHAR,
    ingredient_name VARCHAR,
    recognized_at DATE NOT NULL,
    company_name VARCHAR,
    official_function_raw TEXT,
    official_function_normalized TEXT,
    daily_intake_raw TEXT,
    daily_intake_normalized TEXT,
    precautions_raw TEXT,
    precautions_normalized TEXT,
    source_name VARCHAR NOT NULL,
    CONSTRAINT fk_functional_ingredients_ingredient_master
        FOREIGN KEY (ingredient_master_id) REFERENCES ingredient_master (id)
);

CREATE TABLE notified_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_master_id BIGINT,
    standard_ingredient_name VARCHAR NOT NULL,
    official_function_raw TEXT,
    daily_intake_raw TEXT NOT NULL,
    precautions_raw TEXT,
    source_name VARCHAR NOT NULL,
    CONSTRAINT fk_notified_ingredients_ingredient_master
        FOREIGN KEY (ingredient_master_id) REFERENCES ingredient_master (id)
);

CREATE TABLE product_ingredient_matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    ingredient_master_id BIGINT,
    raw_text TEXT NOT NULL,
    match_method VARCHAR,
    match_status VARCHAR NOT NULL,
    CONSTRAINT fk_product_ingredient_matches_product
        FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT fk_product_ingredient_matches_ingredient_master
        FOREIGN KEY (ingredient_master_id) REFERENCES ingredient_master (id)
);

CREATE TABLE reference_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR NOT NULL UNIQUE,
    title VARCHAR NOT NULL,
    source_type VARCHAR NOT NULL,
    issuer TEXT,
    source_url TEXT,
    local_source_path TEXT,
    parent_source_id BIGINT,
    document_version VARCHAR,
    issued_at_raw VARCHAR,
    effective_from_raw VARCHAR,
    effective_to_raw VARCHAR,
    retrieved_at_raw VARCHAR,
    verification_status VARCHAR NOT NULL,
    section TEXT,
    printed_page VARCHAR,
    pdf_page VARCHAR,
    notes TEXT,
    CONSTRAINT fk_reference_sources_parent
        FOREIGN KEY (parent_source_id) REFERENCES reference_sources (id)
);

CREATE TABLE rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_code VARCHAR NOT NULL UNIQUE,
    scope_type VARCHAR NOT NULL,
    expression_type VARCHAR NOT NULL,
    candidate_examples JSONB,
    judgment_category VARCHAR NOT NULL,
    application_conditions TEXT NOT NULL,
    exceptions TEXT,
    required_evidence TEXT,
    severity VARCHAR NOT NULL,
    rule_version VARCHAR NOT NULL,
    review_status VARCHAR NOT NULL
);

CREATE TABLE rule_ingredients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    ingredient_master_id BIGINT NOT NULL,
    CONSTRAINT fk_rule_ingredients_rule
        FOREIGN KEY (rule_id) REFERENCES rules (id),
    CONSTRAINT fk_rule_ingredients_ingredient_master
        FOREIGN KEY (ingredient_master_id) REFERENCES ingredient_master (id),
    CONSTRAINT uk_rule_ingredients_rule_ingredient
        UNIQUE (rule_id, ingredient_master_id)
);

CREATE TABLE rule_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    reference_source_id BIGINT NOT NULL,
    CONSTRAINT fk_rule_sources_rule
        FOREIGN KEY (rule_id) REFERENCES rules (id),
    CONSTRAINT fk_rule_sources_reference_source
        FOREIGN KEY (reference_source_id) REFERENCES reference_sources (id),
    CONSTRAINT uk_rule_sources_rule_source
        UNIQUE (rule_id, reference_source_id)
);

CREATE TABLE ad_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    case_id VARCHAR NOT NULL UNIQUE,
    case_type VARCHAR NOT NULL,
    ingredient_codes JSONB,
    other_main_ingredients TEXT,
    text_kind VARCHAR,
    quoted_text TEXT,
    source_decision VARCHAR,
    source_reason_summary TEXT,
    printed_page VARCHAR,
    pdf_page VARCHAR,
    verification_status VARCHAR NOT NULL,
    notes TEXT
);

CREATE TABLE rule_cases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT NOT NULL,
    ad_case_id BIGINT NOT NULL,
    CONSTRAINT fk_rule_cases_rule
        FOREIGN KEY (rule_id) REFERENCES rules (id),
    CONSTRAINT fk_rule_cases_ad_case
        FOREIGN KEY (ad_case_id) REFERENCES ad_cases (id),
    CONSTRAINT uk_rule_cases_rule_case
        UNIQUE (rule_id, ad_case_id)
);

CREATE TABLE ad_case_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_case_id BIGINT NOT NULL,
    reference_source_id BIGINT NOT NULL,
    CONSTRAINT fk_ad_case_sources_ad_case
        FOREIGN KEY (ad_case_id) REFERENCES ad_cases (id),
    CONSTRAINT fk_ad_case_sources_reference_source
        FOREIGN KEY (reference_source_id) REFERENCES reference_sources (id),
    CONSTRAINT uk_ad_case_sources_case_source
        UNIQUE (ad_case_id, reference_source_id)
);

CREATE TABLE analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT,
    page_url VARCHAR(2048) NOT NULL,
    page_title VARCHAR(300),
    product_name VARCHAR(200),
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    CONSTRAINT fk_analyses_product
        FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_products_product_name
    ON products (product_name);

CREATE INDEX idx_functional_ingredients_recognition_no
    ON functional_ingredients (recognition_no);

CREATE INDEX idx_functional_ingredients_ingredient_master_id
    ON functional_ingredients (ingredient_master_id);

CREATE INDEX idx_product_ingredient_matches_product_id
    ON product_ingredient_matches (product_id);

CREATE INDEX idx_product_ingredient_matches_ingredient_master_id
    ON product_ingredient_matches (ingredient_master_id);

CREATE INDEX idx_product_ingredient_matches_match_status
    ON product_ingredient_matches (match_status);

CREATE INDEX idx_rules_scope_type
    ON rules (scope_type);

CREATE INDEX idx_rules_severity
    ON rules (severity);

CREATE INDEX idx_rules_review_status
    ON rules (review_status);

CREATE INDEX idx_reference_sources_source_type
    ON reference_sources (source_type);

CREATE INDEX idx_reference_sources_verification_status
    ON reference_sources (verification_status);

CREATE INDEX idx_ad_cases_case_type
    ON ad_cases (case_type);

CREATE INDEX idx_analyses_product_id
    ON analyses (product_id);

CREATE INDEX idx_analyses_created_at
    ON analyses (created_at);
