package db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import tools.jackson.dataformat.csv.CsvMapper;
import tools.jackson.dataformat.csv.CsvSchema;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Types;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 팀원이 준 DB Schema v0.2 참조데이터(CSV 6개, {@code src/main/resources/db/migration/data/})를
 * 1회성으로 Postgres에 적재한다. FK 의존 순서대로 진행한다:
 * ingredient_master(607) → ingredient_synonyms(3,302)/functional_ingredients(773)/
 * notified_ingredients(96) → products(45,970) → product_ingredient_matches(176,447).
 *
 * <p>ingredient_master는 CSV의 id 컬럼값을 그대로 명시 insert한다(1~607 연속값, 나머지
 * 3개 테이블의 ingredientMasterId FK가 이 값을 직접 참조하므로 새로 채번하면 안 됨) — 컬럼이
 * {@code GENERATED BY DEFAULT AS IDENTITY}라 명시값 insert가 가능하고, 끝나고 시퀀스를
 * 608부터 다시 시작하도록 재조정한다.
 *
 * <p>products는 id가 CSV에 없어 자동 채번하고, product_ingredient_matches가 참조하는
 * productReportNo → products.id 매핑은 products 적재가 끝난 뒤 한 번에 조회해서 메모리에
 * 구성한다(45,970건이라 메모리 부담 없음).
 *
 * <p>product_ingredient_matches_v0.2.csv는 {@code docs/data-manifest.md}가 명시한 FINAL
 * 해시(SHA-256 {@code 885848...656010})로 검증된 사본을 사용한다.
 */
public class V4__LoadIngredientReferenceData extends BaseJavaMigration {

    private static final Logger log = LoggerFactory.getLogger(V4__LoadIngredientReferenceData.class);
    private static final int BATCH_SIZE = 1000;

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();

        List<IngredientMasterRow> masters = readCsv("/db/migration/data/ingredient_master_v0.2.csv", IngredientMasterRow.class);
        insertIngredientMaster(connection, masters);
        log.info("ingredient_master {}건 적재 완료", masters.size());

        List<SynonymRow> synonyms = readCsv("/db/migration/data/ingredient_synonyms_v0.2.csv", SynonymRow.class);
        batchInsert(connection,
                "INSERT INTO ingredient_synonyms (ingredient_master_id, raw_text) VALUES (?, ?)",
                synonyms,
                (ps, row) -> {
                    ps.setLong(1, row.ingredientMasterId());
                    ps.setString(2, row.rawText());
                });
        log.info("ingredient_synonyms {}건 적재 완료", synonyms.size());

        List<FunctionalIngredientRow> functionals =
                readCsv("/db/migration/data/functional_ingredients_v0.2.csv", FunctionalIngredientRow.class);
        batchInsert(connection,
                """
                INSERT INTO functional_ingredients
                    (ingredient_master_id, recognition_no, ingredient_name, recognized_at, company_name,
                     official_function_raw, official_function_normalized, daily_intake_raw, daily_intake_normalized,
                     precautions_raw, precautions_normalized, source_name)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                functionals,
                (ps, row) -> {
                    setNullableLong(ps, 1, row.ingredientMasterId());
                    setNullableString(ps, 2, row.recognitionNo());
                    setNullableString(ps, 3, row.ingredientName());
                    ps.setObject(4, LocalDate.parse(row.recognizedAt()));
                    setNullableString(ps, 5, row.companyName());
                    setNullableString(ps, 6, row.officialFunctionRaw());
                    setNullableString(ps, 7, row.officialFunctionNormalized());
                    setNullableString(ps, 8, row.dailyIntakeRaw());
                    setNullableString(ps, 9, row.dailyIntakeNormalized());
                    setNullableString(ps, 10, row.precautionsRaw());
                    setNullableString(ps, 11, row.precautionsNormalized());
                    ps.setString(12, row.sourceName());
                });
        log.info("functional_ingredients {}건 적재 완료", functionals.size());

        List<NotifiedIngredientRow> notifieds =
                readCsv("/db/migration/data/notified_ingredients_v0.2.csv", NotifiedIngredientRow.class);
        batchInsert(connection,
                """
                INSERT INTO notified_ingredients
                    (ingredient_master_id, standard_ingredient_name, official_function_raw, daily_intake_raw,
                     precautions_raw, source_name)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                notifieds,
                (ps, row) -> {
                    setNullableLong(ps, 1, row.ingredientMasterId());
                    ps.setString(2, row.standardIngredientName());
                    setNullableString(ps, 3, row.officialFunctionRaw());
                    ps.setString(4, row.dailyIntakeRaw());
                    setNullableString(ps, 5, row.precautionsRaw());
                    ps.setString(6, row.sourceName());
                });
        log.info("notified_ingredients {}건 적재 완료", notifieds.size());

        List<ProductRow> products = readCsv("/db/migration/data/products_v0.2.csv", ProductRow.class);
        batchInsert(connection,
                """
                INSERT INTO products
                    (product_report_no, product_name, company_name, primary_function_raw,
                     functional_ingredient_raw, product_type, production_status, source_updated_at, source_name)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                products,
                (ps, row) -> {
                    ps.setString(1, row.productReportNo());
                    ps.setString(2, row.productName());
                    ps.setString(3, row.companyName());
                    setNullableString(ps, 4, row.primaryFunctionRaw());
                    setNullableString(ps, 5, row.functionalIngredientRaw());
                    setNullableString(ps, 6, row.productType());
                    setNullableString(ps, 7, row.productionStatus());
                    ps.setObject(8, LocalDate.parse(row.sourceUpdatedAt()));
                    ps.setString(9, row.sourceName());
                });
        log.info("products {}건 적재 완료", products.size());

        Map<String, Long> productIdByReportNo = loadProductIdsByReportNo(connection);

        List<ProductIngredientMatchRow> matches =
                readCsv("/db/migration/data/product_ingredient_matches_v0.2.csv", ProductIngredientMatchRow.class);
        batchInsert(connection,
                """
                INSERT INTO product_ingredient_matches
                    (product_id, ingredient_master_id, raw_text, match_method, match_status)
                VALUES (?, ?, ?, ?, ?)
                """,
                matches,
                (ps, row) -> {
                    Long productId = productIdByReportNo.get(row.productReportNo());
                    if (productId == null) {
                        log.warn("productReportNo={}에 해당하는 products 행을 찾지 못해 스킵", row.productReportNo());
                        ps.setNull(1, Types.BIGINT);
                    } else {
                        ps.setLong(1, productId);
                    }
                    setNullableLong(ps, 2, row.ingredientMasterId());
                    ps.setString(3, row.rawText());
                    setNullableString(ps, 4, row.matchMethod());
                    ps.setString(5, row.matchStatus());
                });
        log.info("product_ingredient_matches {}건 적재 완료", matches.size());
    }

    private static void insertIngredientMaster(Connection connection, List<IngredientMasterRow> rows) throws SQLException {
        batchInsert(connection,
                "INSERT INTO ingredient_master (id, standard_name, ingredient_code, ingredient_category, support_status) "
                        + "VALUES (?, ?, ?, ?, ?)",
                rows,
                (ps, row) -> {
                    ps.setLong(1, row.id());
                    ps.setString(2, row.standardName());
                    setNullableString(ps, 3, row.ingredientCode());
                    ps.setString(4, row.ingredientCategory());
                    ps.setString(5, row.supportStatus());
                });
        try (Statement st = connection.createStatement()) {
            st.execute("ALTER TABLE ingredient_master ALTER COLUMN id RESTART WITH " + (rows.size() + 1));
        }
    }

    private static Map<String, Long> loadProductIdsByReportNo(Connection connection) throws SQLException {
        Map<String, Long> map = new HashMap<>();
        try (Statement st = connection.createStatement();
             ResultSet rs = st.executeQuery("SELECT id, product_report_no FROM products")) {
            while (rs.next()) {
                map.put(rs.getString("product_report_no"), rs.getLong("id"));
            }
        }
        return map;
    }

    @FunctionalInterface
    private interface RowBinder<T> {
        void bind(PreparedStatement ps, T row) throws SQLException;
    }

    private static <T> void batchInsert(Connection connection, String sql, List<T> rows, RowBinder<T> binder)
            throws SQLException {
        try (PreparedStatement ps = connection.prepareStatement(sql)) {
            int count = 0;
            for (T row : rows) {
                binder.bind(ps, row);
                ps.addBatch();
                if (++count % BATCH_SIZE == 0) {
                    ps.executeBatch();
                }
            }
            ps.executeBatch();
        }
    }

    private static void setNullableString(PreparedStatement ps, int index, String value) throws SQLException {
        if (value == null || value.isBlank()) {
            ps.setNull(index, Types.VARCHAR);
        } else {
            ps.setString(index, value);
        }
    }

    private static void setNullableLong(PreparedStatement ps, int index, Long value) throws SQLException {
        if (value == null) {
            ps.setNull(index, Types.BIGINT);
        } else {
            ps.setLong(index, value);
        }
    }

    private static <T> List<T> readCsv(String resourcePath, Class<T> type) {
        CsvMapper csvMapper = new CsvMapper();
        CsvSchema schema = CsvSchema.emptySchema().withHeader().withNullValue("");
        try (InputStream in = V4__LoadIngredientReferenceData.class.getResourceAsStream(resourcePath)) {
            if (in == null) {
                throw new IllegalStateException("리소스를 찾을 수 없음: " + resourcePath);
            }
            return csvMapper.readerFor(type).with(schema).<T>readValues(in).readAll();
        } catch (IOException e) {
            throw new UncheckedIOException("참조데이터 로딩 실패: " + resourcePath, e);
        }
    }

    record IngredientMasterRow(long id, String standardName, String ingredientCode,
                                String ingredientCategory, String supportStatus) {
    }

    record SynonymRow(String rawText, long ingredientMasterId) {
    }

    record FunctionalIngredientRow(String recognitionNo, String ingredientName, String recognizedAt,
                                    String companyName, String officialFunctionRaw, String officialFunctionNormalized,
                                    String dailyIntakeRaw, String dailyIntakeNormalized, String precautionsRaw,
                                    String precautionsNormalized, String sourceName, Long ingredientMasterId) {
    }

    record NotifiedIngredientRow(String standardIngredientName, String officialFunctionRaw, String dailyIntakeRaw,
                                  String precautionsRaw, String sourceName, Long ingredientMasterId) {
    }

    record ProductRow(String productReportNo, String productName, String companyName, String primaryFunctionRaw,
                       String functionalIngredientRaw, String productType, String productionStatus,
                       String sourceUpdatedAt, String sourceName) {
    }

    record ProductIngredientMatchRow(String productReportNo, Long ingredientMasterId, String rawText,
                                      String matchMethod, String matchStatus) {
    }
}
